name: Build and Release Binaries

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build_mac_and_linux:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            archive: tar.gz tar.xz zip
          - target: x86_64-apple-darwin
            os: macos-latest
            archive: tar.gz tar.xz zip
          - target: aarch64-apple-darwin
            os: macos-latest
            archive: tar.gz tar.xz zip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal

      - name: Install Rust Target for Cross-Compilation
        run: rustup target add ${{ matrix.target }}

      - name: Build and test
        run: cargo build --target ${{ matrix.target }} --release --verbose

      - name: Package Binary
        run: |
          if ([[ "${{ matrix.os }}" == "windows-latest" ]]); then
            mkdir -p dist
            cp target/${{ matrix.target }}/release/cartesi-coprocessor.exe dist/
            powershell Compress-Archive -Path dist/* -DestinationPath cartesi-coprocessor-${{ matrix.target }}.zip
          else
            mkdir -p dist
            cp target/${{ matrix.target }}/release/cartesi-coprocessor dist/
            tar -czvf cartesi-coprocessor-${{ matrix.target }}.tar.gz -C dist .
          fi

      - name: Upload Packaged Binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-packaged
          path: |
            cartesi-coprocessor-${{ matrix.target }}.zip
            cartesi-coprocessor-${{ matrix.target }}.tar.gz

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cartesi-coprocessor-${{ matrix.target }}.zip
            cartesi-coprocessor-${{ matrix.target }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_windows:
    runs-on: windows-latest
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            archive: tar.gz tar.xz zip
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal

      - name: Install Rust Target for Cross-Compilation
        run: rustup target add ${{ matrix.target }}

      - name: Build and test
        run: cargo build --target ${{ matrix.target }} --release --verbose

      - name: Package Binary
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/cartesi-coprocessor.exe dist/
          powershell Compress-Archive -Path dist/* -DestinationPath cartesi-coprocessor-${{ matrix.target }}.zip

      - name: Upload Packaged Binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-packaged
          path: |
            cartesi-coprocessor-${{ matrix.target }}.zip
            cartesi-coprocessor-${{ matrix.target }}.tar.gz

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cartesi-coprocessor-${{ matrix.target }}.zip
            cartesi-coprocessor-${{ matrix.target }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
